apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
  namespace: default
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;
        location / {
            add_header Content-Type text/plain;
            return 200 "X-Org-Id: $http_x_org_id\n";
        }
    }
