apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-operator
subjects:
  - kind: ServiceAccount
    name: tenant-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: tenant-operator
  apiGroup: rbac.authorization.k8s.io
