apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-operator
rules:
  - apiGroups: ['mtls.invoisight.com']
    resources: ['tenants']
    verbs: ['*']
  - apiGroups: ['mtls.invoisight.com']
    resources: ['tenants/status']
    verbs: ['get', 'update', 'patch']
  - apiGroups: ['cert-manager.io']
    resources: ['certificates', 'issuers', 'clusterissuers']
    verbs: ['*']
  - apiGroups: ['']
    resources: ['secrets', 'configmaps', 'events', 'namespaces']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'list', 'watch', 'patch']
  - apiGroups: ['apiextensions.k8s.io']
    resources: ['customresourcedefinitions']
    verbs: ['get', 'list', 'watch']
