apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-operator
rules:
  - apiGroups: ['mtls.invoisight.com']
    resources: ['tenants']
    verbs: ['*']
  - apiGroups: ['mtls.invoisight.com']
    resources: ['tenants/status']
    verbs: ['get', 'update', 'patch']
  - apiGroups: ['cert-manager.io']
    resources: ['certificates', 'issuers', 'clusterissuers']
    verbs: ['*']
  - apiGroups: ['']
    resources: ['secrets', 'configmaps', 'events', 'namespaces']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'list', 'watch', 'patch']
  - apiGroups: ['apiextensions.k8s.io']
    resources: ['customresourcedefinitions']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-operator
subjects:
  - kind: ServiceAccount
    name: tenant-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: tenant-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-operator
  template:
    metadata:
      labels:
        app: tenant-operator
    spec:
      serviceAccountName: tenant-operator
      imagePullSecrets:
        - name: regcred
      containers:
        - name: operator
          image: marouandock/invoisight:operator3
          imagePullPolicy: Always
          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'
            requests:
              memory: '128Mi'
              cpu: '250m'
---

