name: Release Helm Chart

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Create temporary directory
        run: mkdir -p temp

      - name: Package Helm chart
        run: |
          helm package charts/mtls-cert-operator -d temp/

      - name: Switch to gh-pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          git pull origin gh-pages || true

      - name: Update Helm repository
        run: |
          # Move any existing .tgz files to temp directory to preserve history
          mv *.tgz temp/ 2>/dev/null || true
          
          # Generate or update index using all charts in temp directory
          helm repo index temp/ --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          
          # Move everything back
          mv temp/* .
          rm -rf temp
          
          # Commit and push
          git add .
          git commit -m "Update Helm repository [skip ci]" || echo "No changes to commit"
          git push origin gh-pages